### PR TITLE
Fix lastOn and lastOff for virtual switch

### PR DESCRIPTION
**Pull request by notoriousbdg**

### CODE REVIEW

**Comment by cooperglee** [comment]
lastOn and lastOff are local variables and not from the history - they should update as it is used...   Are you the fields being populated after use?  It could be Android related if not and I do not have an Android to test on

**Comment by notoriousbdg** [comment]
I have tried with and without the attribute definition and the tiles only display values when the attribute definition is present.  I only have Android devices to test with, so it's possible that it's an Android specific issue.

**Comment by cooperglee** [comment]
It will only work with the attribute definition present...  It will not ever have values when it is first installed - they don't exist...  Are you getting values after you turn it on/off or nothing at all?  If not at all then I will look into it a bit further - if you are getting values then it is working as expected - I could/will supplant a value of "Just Installed" so that there is something there as supposed to "null" for initial install

**Comment by notoriousbdg** [comment]
Without the attribute definition, the lastOn and lastOff tiles are blank when turning the switch on and off.  Once I add the attribute definition, the lastOn and lastOff tiles work as expected.  If I remove the attribute definition the tiles become blank again.  Add the attribute definition back, and they work again.

**Pull request merged**
